[package]
name = "solidgate-connector"
version = "0.5.3"
edition = "2021"
authors = ["gorin <mxmgorin@gmail.com>"]

[dependencies]
flurl = { git = "https://github.com/MyJetTools/fl-url.git", tag = "0.6.1" }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["full"] }
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
